/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Pinksaleabi } from "./Pinksaleabi";
export * as factories from "./factories";
export { Pinksaleabi__factory } from "./factories/Pinksaleabi__factory";
